### ISSUE TITLE
Crash on server load

### ISSUE THREAD

**Issue by darkphan** [MysticMods/MysticalLib#13]
Version: 1.2.0
Crash log: https://pste.me/#/PEMvF

**Comment by EpicSquid** [comment]
I am genuinely confused how this bug exists. Will have to look into it further

**Comment by noobanidus** [comment]
There were two missing `@SideOnly`s on the TrapDoor and ... PressurePlate. Hopefully this fixes it, just need @EpicSquid to push a new build. Actually, I'll go test it in a server build locally now.

**Comment by noobanidus** [comment]
Found another and now have it fully functional -- in a dev environment at the very least. It seems the Door one was also missing a SideOnly. If @EpicSquid can push a build out tomorrow, that'll hopefully fix it for you.

**Comment by dmauldin** [comment]
Sweet, thanks!  Having this same issue.  Reverting to 1.1.1 for now.  👍
