### ISSUE TITLE
Crash when trying to spawn amethyst after adding to Enigmatica 2

### ISSUE THREAD

**Issue by Degsdegsdegs** [MysticMods/MysticalLib#18]
Hello!  I have a weird issue, I tried adding mystical lib/world and Roots 3 to an Enigmatica 2 server. It seems that whenever amethyst tries to spawn, it crashes.  Disabling amethyst lets the server run but obviously, no amethyst.

[Crash log.](https://pastebin.com/XFx232Bb)

**Comment by Degsdegsdegs** [comment]
[Link to the enigmatica 2 github issue](https://github.com/NillerMedDild/Enigmatica2/issues/509)

**Comment by noobanidus** [comment]
A couple of questions for you:

- Can you attach your Mystical World config for when this crash happens?
- Specifically, is `gems`'s `B:enableOres` set to true?

Technically the only situation where this could happen is either a) there's a discontinuty between the registered amethyst enum entry (next to impossible), or b) gems are enabled, ores are disabled, but the number of ore to spawn per chunk is not 0.

Either way, there should be a null check in there.

**Comment by noobanidus** [comment]
I've pushed a potential fix to the Mystical World repository but that would merely mask the issue, as I don't think amethyst would spawn. For some reason it's not registering amethyst's ore block (hence the null value), and that would only happen if `ConfigManager.gems.enableOres` is set to false, so if you could triple-check your config for me, that would be great.

**Comment by Degsdegsdegs** [comment]
[The config as it was during the crash](https://pastebin.com/mM6tQau1)

Looks like you were correct, in the gems section I had 

enableAmythest=true

but

enableOres=false

Sorry about that!

**Comment by noobanidus** [comment]
No worries, it exposed the fact that I was checking "hasGem" instead of "hasOre" when trying to generate -- so there was a bug there as well!
