### ISSUE TITLE
Mod crashes minecraft on launching

### ISSUE THREAD

**Issue by tadakino95** [MysticMods/MysticalLib#26]
https://pastebin.com/xYpenrYn

Here's the crash log!! I'm sorry but I'm rather new to github so I hope I did everything right.
I added mysticmods and mysticallib to a custom modpack and that crashed minecraft when I was launching the pack. The pack launched per normal once I removed both mods.

**Comment by noobanidus** [comment]
Please update to MysticalLib 1.3.8. Unfortunately these errors occur well before the warning that says "hey you need a higher version for this". I'd like to work out why, to be honest...

**Comment by tadakino95** [comment]
Ahh that makes sense, it's weird since I downloaded the mod directly from
the twitch launcher so I thought I'd already have the latest version. My
bad! I'll update and try again!

**Comment by noobanidus** [comment]
You may need to hit refresh a bunch of times in the Twitch launcher, as it's possible it's got some out-of-date info on the l ibrary but has the latest version of the mod...

**Comment by thisisACat5** [comment]
> You may need to hit refresh a bunch of times in the Twitch launcher, as it's possible it's got some out-of-date info on the l ibrary but has the latest version of the mod...

I had the same problem but that didn't help
