### ISSUE TITLE
New version crashes minecraft upon launch

### ISSUE THREAD

**Issue by AndreiNdi** [MysticMods/MysticalLib#30]
Hi,

I am trying to upgrade from version 1.3.7 to 1.3.8 but the game just crashes with the latest .jar.

Here is the log:
https://paste.ee/p/buSvU

Hopefully, it's just something that I am doing something wrong :)

Edit: Sorry, this might actually be a Mystical World issue as Mystical Lib 1.3.8 + Mystical World 1.4.4 seems to work, but I can't tell what is causing the issue.

**Comment by noobanidus** [comment]
[1.4.0 is the latest version; you nee dto be running that, not 1.3.8](https://www.curseforge.com/minecraft/mc-mods/mysticallib/files/2817910)

**Comment by AndreiNdi** [comment]
I am not sure how I managed to get the latest version only for Mystical World, I downloaded both 30 minutes ago. Works as expected with 1.4.0, apologies for the inconvenience.

**Comment by noobanidus** [comment]
No worries, Twitch is a little fickle.
