### ISSUE TITLE
Crash with Mystical World and JEI referencing Mysticallib

### ISSUE THREAD

**Issue by Halfdeaf** [MysticMods/MysticalLib#31]
I'm not sure if this is you or JEI. Please correct me if I'm wrong but both are referenced in the crash report. This is mysticallib-1.14.4-1.6.0 in Enigmatica 4

Crashes when clicking on anvil recipe for Mystical World in JEI

Tested on Lead and Copper Chestplate and Quicksilver Helmet

https://gist.github.com/Halfdeaf/9736ac65b3fd81fa986e6b2af5938c2a

**Comment by noobanidus** [comment]
Yes, this is a known issue. It's a relatively rare occurrence so I haven't released an immediate fix, but it will be included in the next version that will hopefully be released this weekend.

**Comment by Halfdeaf** [comment]
Yeah, I just saw that it was reported on Mystical world. I did not catch that when I reported. Not a high priority in my opinion, easy to avoid when you know about it
