### ISSUE TITLE
mcmod.info wrong version number

### ISSUE THREAD

**Issue by xJon** [MysticMods/MysticalLib#36]
The mod ships with an `mcmod.info` file that has a wrong version number, just FYI!

**Comment by noobanidus** [comment]
Goddamn! I thought I'd fixed that. Thanks for the heads-up, it's supposed to auto-replace but I guess I messed up that part of the gradle file.

**Comment by xJon** [comment]
No worries, your lightning-speed reply makes up for it!

**Comment by xJon** [comment]
(This was still the case in `1.7.0`).

**Comment by noobanidus** [comment]
Okay, solution is I go fix it *right* now so I d on't forget -- although it won't be in until the next release.

**Comment by noobanidus** [comment]
Okay, so the auto-replacer was set up but the actual mcmod.info file was manually hand-coded to a specific version, urgh.
