### ISSUE TITLE
Roots, Mystical Lib, and Mystical World are Up to Date

### ISSUE THREAD

**Issue by PhylsorKyrem** [MysticMods/MysticalLib#38]
---- Minecraft Crash Report ----
// Shall we play a game?

Time: 2020-04-05 22:18:36 EDT
Description: Initializing game

java.lang.RuntimeException: Invalid id 4096 - maximum id range exceeded.
    at net.minecraftforge.registries.ForgeRegistry.add(ForgeRegistry.java:295)
    at net.minecraftforge.registries.ForgeRegistry.add(ForgeRegistry.java:281)
    at net.minecraftforge.registries.ForgeRegistry.register(ForgeRegistry.java:113)
    at epicsquid.mysticallib.LibRegistry.registerBlocks(LibRegistry.java:142)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_2653_LibRegistry_registerBlocks_Register.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
    at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:144)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
    at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:845)
    at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:630)
    at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
    at net.minecraft.client.Minecraft.init(Minecraft.java:467)
    at net.minecraft.client.Minecraft.run(Minecraft.java:3931)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
  Minecraft Version: 1.12.2
  Operating System: Windows 10 (amd64) version 10.0
  Java Version: 1.8.0_51, Oracle Corporation
  Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
  Memory: 952570344 bytes (908 MB) / 1668284416 bytes (1591 MB) up to 3008888832 bytes (2869 MB)
  JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx3228m -Xms256m -XX:PermSize=256m
  IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
  FML: MCP 9.42 Powered by Forge 14.23.5.2847 162 mods loaded, 160 mods active
       States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
       
       | State | ID                                           | Version                | Source                                                | Signature                                |
       |:----- |:-------------------------------------------- |:---------------------- |:----------------------------------------------------- |:---------------------------------------- |
       | LCH   | minecraft                                    | 1.12.2                 | minecraft.jar                                         | None                                     |
       | LCH   | mcp                                          | 9.42                   | minecraft.jar                                         | None                                     |
       | LCH   | FML                                          | 8.0.99.99              | forge-1.12.2-14.23.5.2847.jar                         | None                                     |
       | LCH   | forge                                        | 14.23.5.2847           | forge-1.12.2-14.23.5.2847.jar                         | None                                     |
       | LCH   | com.elytradev.movingworld.common.asm.coremod |                        | minecraft.jar                                         | None                                     |
       | LCH   | foamfixcore                                  | 7.7.4                  | minecraft.jar                                         | None                                     |
       | LCH   | futuremccore                                 | 0.1.12                 | minecraft.jar                                         | None                                     |
       | LCH   | forgeendertech                               | 1.12.2-4.5.1.0         | ForgeEndertech-1.12.2-4.5.1.0-build.0454.jar          | None                                     |
       | LCH   | adhooks                                      | 1.12.2-3.2.3.0         | AdHooks-1.12.2-3.2.3.0-build.0435.jar                 | None                                     |
       | LCH   | antiqueatlas                                 | 4.6.3                  | antiqueatlas-1.12.2-4.6.3.jar                         | None                                     |
       | LCH   | antiqueatlasoverlay                          | 1.2                    | antiqueatlas-1.12.2-4.6.3.jar                         | None                                     |
       | LCH   | mantle                                       | 1.12-1.3.3.55          | Mantle-1.12-1.3.3.55.jar                              | None                                     |
       | LCH   | inspirations                                 | 1.12.2-0.2.9           | Inspirations-1.12.2-0.2.9.jar                         | None                                     |
       | LCH   | placebo                                      | 1.6.0                  | Placebo-1.12.2-1.6.0.jar                              | None                                     |
       | LCH   | apotheosis                                   | 1.12.4                 | Apotheosis-1.12.2-1.12.5.jar                          | None                                     |
       | LCH   | jei                                          | 4.15.0.291             | jei_1.12.2-4.15.0.291.jar                             | None                                     |
       | LCH   | appleskin                                    | 1.0.9                  | AppleSkin-mc1.12-1.0.9.jar                            | None                                     |
       | LCH   | aquaculture                                  | 1.6.8                  | Aquaculture-1.12.2-1.6.8.jar                          | None                                     |
       | LCH   | ebwizardry                                   | 4.2.10                 | ElectroblobsWizardry-4.2.10-MC1.12.2.jar              | None                                     |
       | LCH   | arcane_essentials                            | 1.0                    | Arcane Essentials-0.9.2.jar                           | None                                     |
       | LCH   | astikorcarts                                 | 1.12.2-0.1.2.7         | astikorcarts-1.12.2-0.1.2.7.jar                       | None                                     |
       | LCH   | baubles                                      | 1.5.2                  | Baubles-1.12-1.5.2.jar                                | None                                     |
       | LCH   | crafttweaker                                 | 4.1.20                 | CraftTweaker2-1.12-4.1.20.jar                         | None                                     |
       | LCH   | astralsorcery                                | 1.10.22                | astralsorcery-1.12.2-1.10.23.jar                      | a0f0b759d895c15ceb3e3bcb5f3c2db7c582edf0 |
       | LCH   | athenaeum                                    | 1.12.2-1.17.4          | athenaeum-1.12.2-1.17.4.jar                           | None                                     |
       | LCH   | quark                                        | r1.6-178               | Quark-r1.6-178.jar                                    | None                                     |
       | LCH   | autoreglib                                   | 1.3-32                 | AutoRegLib-1.3-32.jar                                 | None                                     |
       | LCH   | gorecore                                     | 1.12.2-0.4.5           | avatarmod-1.5.17-alpha.jar                            | None                                     |
       | LCH   | avatarmod                                    | 1.5.17-alpha           | avatarmod-1.5.17-alpha.jar                            | None                                     |
       | LCH   | tconstruct                                   | 1.12.2-2.13.0.183      | TConstruct-1.12.2-2.13.0.183.jar                      | None                                     |
       | LCH   | mmdlib                                       | 1.0.0-rc2              | MMDLib-1.12-1.0.0-rc2.36.jar                          | None                                     |
       | LCH   | thaumcraft                                   | 6.1.BETA26             | Thaumcraft-1.12.2-6.1.BETA26.jar                      | None                                     |
       | LCH   | basemetals                                   | 2.5.0-rc2              | BaseMetals-1.12-2.5.0-rc2.332.jar                     | d476d1b22b218a10d845928d1665d45fce301b27 |
       | LCH   | betteradvancements                           | 0.1.0.77               | BetterAdvancements-1.12.2-0.1.0.77.jar                | None                                     |
       | LCH   | betterquesting                               | 3.5.323                | BetterQuesting-3.5.323.jar                            | None                                     |
       | LCH   | patchouli                                    | 1.0-20                 | Patchouli-1.0-20.jar                                  | None                                     |
       | LCH   | bewitchment                                  | 0.21.11                | bewitchment-1.12.2-0.0.21.11.jar                      | None                                     |
       | LCH   | bookshelf                                    | 2.3.590                | Bookshelf-1.12.2-2.3.590.jar                          | d476d1b22b218a10d845928d1665d45fce301b27 |
       | LCH   | boundbaubles                                 | 0.1                    | boundbaubles-0.2.jar                                  | None                                     |
       | LCH   | bountifulbaubles                             | 0.0.1                  | Bountiful Baubles-1.12.2-0.1.5.jar                    | None                                     |
       | LCH   | forgelin                                     | 1.8.4                  | Forgelin-1.8.4.jar                                    | None                                     |
       | LCH   | bountiful                                    | 2.2.1                  | Bountiful-2.2.1.jar                                   | None                                     |
       | LCH   | bullseye                                     | 3.0.7                  | Bullseye-1.12.2-3.0.7.jar                             | None                                     |
       | LCH   | callablehorses                               | 1.0                    | CallableHorses MC1.12.2 v1.0.jar                      | None                                     |
       | LCH   | chiselsandbits                               | 14.33                  | chiselsandbits-14.33.jar                              | None                                     |
       | LCH   | combatica-api                                | 1.12.2-1.2.0           | combatica-api-1.12.2-1.2.0.jar                        | None                                     |
       | LCH   | combatica                                    | 1.12.2-0.1.0.5-beta5   | combatica-1.12.2-0.1.0.5-beta5.jar                    | None                                     |
       | LCH   | comforts                                     | 1.4.1.3                | comforts-1.12.2-1.4.1.3.jar                           | 2484ef4d131fdc0dca0647aa21b7b944ddb935a1 |
       | LCH   | cosmeticarmorreworked                        | 1.12.2-v4b             | CosmeticArmorReworked-1.12.2-v4b.jar                  | aaaf83332a11df02406e9f266b1b65c1306f0f76 |
       | LCH   | craftablehorsearmour                         | 1.3                    | CraftableHorseArmour-1.3.0-1.12.jar                   | None                                     |
       | LCH   | ctgui                                        | 1.0.0                  | CraftTweaker2-1.12-4.1.20.jar                         | None                                     |
       | LCH   | crafttweakerjei                              | 2.0.3                  | CraftTweaker2-1.12-4.1.20.jar                         | None                                     |
       | LCH   | ctm                                          | MC1.12.2-1.0.2.31      | CTM-MC1.12.2-1.0.2.31.jar                             | None                                     |
       | LCH   | customnpcs                                   | 1.12                   | CustomNPCs_1.12.2-(01Oct19).jar                       | None                                     |
       | LCH   | dimdoors                                     | 3.0.9+287              | DimensionalDoors-3.0.9-287.jar                        | None                                     |
       | LCH   | dropt                                        | 1.12.2-1.17.0          | dropt-1.12.2-1.17.0.jar                               | None                                     |
       | LCH   | dungeontactics                               | DT-0.16.6              | DungeonTactics-1.12.2-0.16.6.jar                      | None                                     |
       | LCH   | fantasticlib                                 | 1.12.2.034             | FantasticLib-1.12.2.034.jar                           | None                                     |
       | LCH   | dynamicstealth                               | 1.12.2.102             | DynamicStealth-1.12.2.102.jar                         | None                                     |
       | LCH   | sereneseasons                                | 1.2.18                 | SereneSeasons-1.12.2-1.2.18-universal.jar             | None                                     |
       | LCH   | orelib                                       | 3.6.0.1                | OreLib-1.12.2-3.6.0.1.jar                             | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
       | LCH   | dsurround                                    | 3.6.0.2                | DynamicSurroundings-1.12.2-3.6.0.2.jar                | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
       | LCH   | embers                                       | 1.13-hotfix2           | EmbersRekindled-1.13-hotfix2.jar                      | None                                     |
       | LCH   | eplus                                        | 5.0.176                | EnchantingPlus-1.12.2-5.0.176.jar                     | d476d1b22b218a10d845928d1665d45fce301b27 |
       | LCH   | enchdesc                                     | 1.1.15                 | EnchantmentDescriptions-1.12.2-1.1.15.jar             | d476d1b22b218a10d845928d1665d45fce301b27 |
       | LCH   | minerva                                      | 1.0.13                 | minerva-library-1.0.13.jar                            | b851b8b7c7f4d8d0e910ff27618150ba80c026ec |
       | LCH   | extraalchemy                                 | 0.5.3                  | extraalchemy-0.5.3.jar                                | b851b8b7c7f4d8d0e910ff27618150ba80c026ec |
       | LCH   | extra_spells                                 | 1.1.4                  | ExtraSpells-1.12.2-1.1.4.jar                          | None                                     |
       | LCH   | foamfix                                      | 0.10.10-1.12.2         | foamfix-0.10.10-1.12.2.jar                            | None                                     |
       | LCH   | minecraftfuture                              | 0.1.13                 | future-mc-0.1.13.jar                                  | None                                     |
       | LCH   | grapplemod                                   | 1.12.2-v11.1           | grapplemod-v11.1-1.12.2.jar                           | None                                     |
       | LCH   | hammercore                                   | 2.0.6.14               | HammerLib-1.12.2-2.0.6.14.jar                         | 9f5e2a811a8332a842b34f6967b7db0ac4f24856 |
       | LCH   | heroicarmory                                 | 1.1.3                  | heroicarmory-1.2.0.jar                                | None                                     |
       | LCH   | historicizedmedicine                         | 1.12.2a                | historicizedmedicine-1.3.9.5.jar                      | None                                     |
       | LCH   | horsetweaks                                  | 1.0.5                  | HorseTweaks_1.12.2-1.0.5.jar                          | None                                     |
       | LCH   | huntersdream                                 | 1.1.2                  | Hunter's Dream-1.12.2-1.1.2.jar                       | None                                     |
       | LCH   | llibrary                                     | 1.7.19                 | llibrary-1.7.19-1.12.2.jar                            | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
       | LCH   | iceandfire                                   | 1.8.4                  | iceandfire-1.8.4.jar                                  | None                                     |
       | LCH   | improvableskills                             | 65r                    | ImprovableSkills-1.12.2-65r.jar                       | 4d7b29cd19124e986da685107d16ce4b49bc0a97 |
       | LCH   | improvedbackpacks                            | 1.12.2-1.5.0.0         | ImprovedBackpacks-1.12.2-1.5.0.0.jar                  | None                                     |
       | LCH   | harvestcraft                                 | 1.12.2zb               | Pam's HarvestCraft 1.12.2zg.jar                       | None                                     |
       | LCH   | jehc                                         | 1.7.0                  | just-enough-harvestcraft-1.12.2-1.7.0.jar             | None                                     |
       | LCH   | leatherworks                                 | 1.78.0                 | LeatherWorks-1.12-1.78.0.42.jar                       | None                                     |
       | LCH   | shotgunsandglitter                           | 1.6                    | shotgunsandglitter-1.6.jar                            | None                                     |
       | LCH   | librarianlib                                 | 4.20                   | librarianlib-1.12.2-4.20-release.jar                  | None                                     |
       | LCH   | livingenchantment                            | 3.2.1                  | living_enchantment-3.2.1.jar                          | None                                     |
       | LCH   | matchlockweapons                             | 0.8                    | Matchlock Guns Mod-1.12.2-7a.jar                      | None                                     |
       | LCH   | metallurgy                                   | 0.3.3                  | Metallurgy-4-Reforged-0.3.3.jar                       | None                                     |
       | LCH   | millenaireextendedbyzantine                  | 1.0.0                  | Millénaire Extended - Byzantine-1.12.2-1.0.0.jar      | None                                     |
       | LCH   | millenaireextendedinuits                     | 1.0.0                  | Millénaire Extended - Inuits-1.12.2-1.0.0.jar         | None                                     |
       | LCH   | millenaireextendedmaya                       | 1.0.0                  | Millénaire Extended - Maya-1.12.2-1.0.0.jar           | None                                     |
       | LCH   | millenaireextendednormans                    | 1.1.1                  | Millénaire Extended - Normans-1.12.2-1.1.1.jar        | None                                     |
       | LCH   | millenaire                                   | Millénaire 8.0.1       | millenaire-1.12.2-8.0.1.jar                           | None                                     |
       | LCH   | som                                          | 1.2.10-mc1.12.2        | MK1.12.2-1.2.10.jar                                   | None                                     |
       | LCH   | targeting_api                                | 0.15                   | targeting_api-0.15.jar                                | None                                     |
       | LCH   | mkultra                                      | 0.99.12                | MKUltra-0.99.12.jar                                   | None                                     |
       | LCH   | modnametooltip                               | 1.10.1                 | modnametooltip_1.12.2-1.10.1.jar                      | None                                     |
       | LCH   | movingworld                                  | 1.12-6.342             | movingworld-1.12-6.342-full.jar                       | None                                     |
       | LCH   | multimob                                     | 1.0.5                  | multimob-1.0.5.jar                                    | None                                     |
       | LCH   | roots                                        | 1.12.2-3.0.26          | Roots-1.12.2-3.0.26.jar                               | None                                     |
       | LCH   | mysticalworld                                | 1.12.2-1.8.3           | mysticalworld-1.12.2-1.8.3.jar                        | None                                     |
       | LCH   | naturescompass                               | 1.8.5                  | NaturesCompass-1.12.2-1.8.5.jar                       | None                                     |
       | LCH   | bq_npc_integration                           | 3.4.34                 | NPCIntegration-3.4.34.jar                             | None                                     |
       | LCH   | orespawn                                     | 3.3.1                  | OreSpawn-1.12-3.3.1.179.jar                           | d476d1b22b218a10d845928d1665d45fce301b27 |
       | LCH   | overpoweredarmorbar                          | @VERSION@              | overloadedarmorbar-1.0.4g.jar                         | None                                     |
       | LCH   | plants2                                      | 2.10.7                 | Plants-1.12.2-2.10.7.jar                              | None                                     |
       | LCH   | potioncore                                   | 1.9_for_1.12.2         | PotionCore-1.9_for_1.12.2.jar                         | None                                     |
       | LCH   | primitivemobs                                | 1.2.3a                 | primitivemobs-1.2.3a.jar                              | None                                     |
       | LCH   | pyrotech                                     | 1.12.2-1.4.23          | pyrotech-1.12.2-1.4.23.jar                            | None                                     |
       | LCH   | qualitytools                                 | 1.0.7_for_1.12.2       | QualityTools-1.0.7_for_1.12.2.jar                     | None                                     |
       | LCH   | questbook                                    | 3.1.1-1.12             | questbook-3.1.1-1.12.jar                              | None                                     |
       | LCH   | randomenchantments                           | @VERSION@              | randomenchants-0.1.4a.jar                             | None                                     |
       | LCH   | realdrops                                    | 1.2.14                 | RealisticItemDrops-1.2.14.jar                         | None                                     |
       | LCH   | xreliquary                                   | 1.12.2-1.3.4.796       | Reliquary-1.12.2-1.3.4.796.jar                        | None                                     |
       | LCH   | roguelike                                    | 1.8.0                  | RoguelikeDungeons-1.12.2-1.8.0.jar                    | None                                     |
       | LCH   | roughtweaks                                  | 1.0                    | roughTweaks0.2.4-1.12.2.jar                           | None                                     |
       | LCH   | subcommonlib                                 | 1.2.0.1                | subcommonlib-sublib-1.12.2-1.2.0.4.jar                | None                                     |
       | LCH   | rpginventory                                 | 1.12.2                 | rpginventory-1.12-5.3.0.0.jar                         | None                                     |
       | LCH   | rustic                                       | 1.1.2                  | rustic-1.1.2.jar                                      | None                                     |
       | LCH   | rusticthaumaturgy                            | 4.4a                   | Rustic Thaumaturgy-4.4a.jar                           | None                                     |
       | LCH   | setbonus                                     | 1.12.2.019             | SetBonus-1.12.2.019.jar                               | None                                     |
       | LCH   | simpleharvest                                | 1.08                   | simpleharvest-1.08.jar                                | None                                     |
       | LCH   | sit                                          | v1.3                   | sit-1.12.2-v1.3.jar                                   | None                                     |
       | LCH   | soot                                         | 1.6                    | Soot-1.6.jar                                          | None                                     |
       | LCH   | spartanweaponry                              | beta 1.3.8             | SpartanWeaponry-1.12.2-beta-1.3.8.jar                 | None                                     |
       | LCH   | spartanbm                                    | 0.3                    | spartanbm-0.3.jar                                     | None                                     |
       | LCH   | spartanfire                                  | 0.07                   | spartanfire-0.07.jar                                  | None                                     |
       | LCH   | spartanshields                               | 1.5.4                  | SpartanShields-1.12.2-1.5.4.jar                       | None                                     |
       | LCH   | spartanweaponryarcana                        | beta 1.0.3             | SpartanWeaponryArcana-1.12.2-beta-1.0.3.jar           | None                                     |
       | LCH   | bq_standard                                  | 3.4.173                | StandardExpansion-3.4.173.jar                         | None                                     |
       | LCH   | stg                                          | 1.12.2-1.2.3           | stg-1.12.2-1.2.3.jar                                  | None                                     |
       | LCH   | tails                                        | 1.12-1.10.0            | Tails-1.12-1.10.0.jar                                 | None                                     |
       | LCH   | tetra                                        | 0.39.1                 | tetra-1.12.2-0.39.1.jar                               | None                                     |
       | LCH   | tg                                           | 0.1.5.0                | Thaumic_Gadgets_1.12.2_0.1.5.1_tb.26.jar              | None                                     |
       | LCH   | thaumicaugmentation                          | 1.12.2-1.1.17          | ThaumicAugmentation-1.12.2-1.1.17.jar                 | 8f678591ba6f78d579e553a8aa94b4c4766cb13d |
       | LCH   | thaumicperiphery                             | 0.3.1                  | thaumicperiphery-0.3.1.jar                            | None                                     |
       | LCH   | toughnessbar                                 | @VERSION@              | toughnessbar-2.4.jar                                  | None                                     |
       | LCH   | traverse                                     | 1.6.0                  | Traverse-1.12.2-1.6.0-69.jar                          | None                                     |
       | LCH   | xat                                          | 0.29.2                 | Trinkets and Baubles-1.12.2-0.29.2.jar                | None                                     |
       | LCH   | ultimate_unicorn_mod                         | 1.5.16                 | ultimate_unicorn_mod-1.12.2-1.5.16.jar                | None                                     |
       | LCH   | valkyrienskies                               | 1.0-alpha-1            | ValkyrienSkies-1.12.2-1.0-alpha-1.jar                 | None                                     |
       | LCH   | vs_open_computers                            | 1.0-alpha-1            | ValkyrienSkies-1.12.2-1.0-alpha-1.jar                 | None                                     |
       | LCH   | vs_world                                     | 1.0-alpha-1            | ValkyrienSkies-1.12.2-1.0-alpha-1.jar                 | None                                     |
       | LCH   | vs_control                                   | 1.0-alpha-1            | ValkyrienSkies-1.12.2-1.0-alpha-1.jar                 | None                                     |
       | LCH   | vanillafix                                   | 1.0.10-150             | VanillaFix-1.0.10-150.jar                             | None                                     |
       | LCH   | villagenames                                 | 3.3.1                  | VillageNames-1.12.2-3.3.1.jar                         | None                                     |
       | LCH   | wildcraft                                    | 1.0                    | WildCraft-1.12.2- 1.0.1.0- F14.23.2.2611.jar          | None                                     |
       | LCH   | wings                                        | 1.1.6                  | wings-1.1.6-1.12.2.jar                                | None                                     |
       | LCH   | bauble_wings                                 | 1.0.0                  | wings-1.1.6-1.12.2.jar                                | None                                     |
       | LCH   | wolfarmor                                    | 2.2.3.6                | wolfarmor-1.12.2-2.2.3.1798-universal.jar             | None                                     |
       | LCH   | drplibrary                                   | 1.12.2-0.1.3-SNAPSHOT  | drplibrary-1.12.2-0.1.3-SNAPSHOT-20190129.034240.jar  | 893c317856cf6819b3a8381c5664e4b06df7d1cc |
       | LCH   | drpcmblueprints                              | 1.12.2-1.2.3           | drpcmblueprints-1.12.2-1.2.3.jar                      | 893c317856cf6819b3a8381c5664e4b06df7d1cc |
       | LCH   | drpcmmaarg                                   | 1.12.2-0.10.0-SNAPSHOT | drpcmmaarg-1.12.2-0.10.0-SNAPSHOT-20181116.074036.jar | 893c317856cf6819b3a8381c5664e4b06df7d1cc |
       | LCH   | drpcmguis                                    | 1.12.2-0.0.2-SNAPSHOT  | drpcmguis-1.12.2-0.0.1-SNAPSHOT-20181125.120253.jar   | 893c317856cf6819b3a8381c5664e4b06df7d1cc |
       | LCH   | drpcore                                      | 1.12.2-0.4.7           | drpcore-1.12.2-0.4.8.jar                              | 893c317856cf6819b3a8381c5664e4b06df7d1cc |
       | LCH   | drpcmlocks                                   | 1.12.2-1.0.1           | drpcmlocks-1.12.2-1.0.0-SNAPSHOT-20181126.111203.jar  | 893c317856cf6819b3a8381c5664e4b06df7d1cc |
       | LCH   | drpmedieval                                  | 1.12.2-0.3.6           | drpmedieval-1.12.2-0.3.6.jar                          | None                                     |
       | LCH   | phosphor-lighting                            | 1.12.2-0.2.6           | phosphor-1.12.2-0.2.6+build50-universal.jar           | f0387d288626cc2d937daa504e74af570c52a2f1 |
       | LCH   | librarianliblate                             | 4.20                   | librarianlib-1.12.2-4.20-release.jar                  | None                                     |
       | LCH   | mysticallib                                  | 1.12.2-1.7.0           | mysticallib-1.12.2-1.7.0.jar                          | None                                     |
       | UD    | mowzies_wings                                | 1.0.0                  | wings-1.1.6-1.12.2.jar                                | None                                     |
       | UD    | mobends_wings                                | 1.0.0                  | wings-1.1.6-1.12.2.jar                                | None                                     |
  Loaded coremods (and transformers): CorePlugin (ForgeEndertech-1.12.2-4.5.1.0-build.0454.jar)
                                        
                                      wings (wings-1.1.6-1.12.2.jar)
                                        me.paulf.wings.server.asm.WingsRuntimePatcher
                                        me.paulf.wings.server.asm.mobends.WingsMoBendsRuntimePatcher
                                      SSLoadingPlugin (SereneSeasons-1.12.2-1.2.18-universal.jar)
                                        sereneseasons.asm.transformer.EntityRendererTransformer
                                        sereneseasons.asm.transformer.WorldTransformer
                                      Thaumic Augmentation Core Plugin (ThaumicAugmentation-1.12.2-1.1.17.jar)
                                        thecodex6824.thaumicaugmentation.core.TATransformer
                                      ForgelinPlugin (Forgelin-1.8.4.jar)
                                        
                                      AstralCore (astralsorcery-1.12.2-1.10.23.jar)
                                        
                                      TransformLoader (DynamicSurroundings-1.12.2-3.6.0.2.jar)
                                        
                                      HCASM (HammerLib-1.12.2-2.0.6.14.jar)
                                        com.zeitheron.hammercore.asm.HammerCoreTransformer
                                      ApotheosisCore (Apotheosis-1.12.2-1.12.5.jar)
                                        shadows.ApotheosisTransformer
                                      CTMCorePlugin (CTM-MC1.12.2-1.0.2.31.jar)
                                        team.chisel.ctm.client.asm.CTMTransformer
                                      llibrary (llibrary-core-1.0.11-1.12.2.jar)
                                        net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
                                        net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
                                      LibrarianLib Plugin (librarianlib-1.12.2-4.20-release.jar)
                                        com.teamwizardry.librarianlib.asm.LibLibTransformer
                                      Quark Plugin (Quark-r1.6-178.jar)
                                        vazkii.quark.base.asm.ClassTransformer
                                      iceandfire (iceandfire-1.8.4.jar)
                                        com.github.alexthe666.iceandfire.patcher.IceAndFireRuntimePatcher
                                      VanillaFixLoadingPlugin (VanillaFix-1.0.10-150.jar)
                                        
                                      PhosphorFMLLoadingPlugin (phosphor-1.12.2-0.2.6+build50-universal.jar)
                                        
                                      FutureMC (future-mc-0.1.13.jar)
                                        thedarkcolour.futuremc.asm.CoreTransformer
                                      Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.10-1.12.2.jar)
                                        pl.asie.foamfix.coremod.FoamFixTransformer
                                      MixinLoaderForge (ValkyrienSkies-1.12.2-1.0-alpha-1.jar)
                                        
                                      BewitchmentFMLLoadingPlugin (bewitchment-1.12.2-0.0.21.11.jar)
                                        
                                      MovingWorldCore (movingworld-1.12-6.342-full.jar)
  GL info: ' Vendor: 'Intel' Version: '4.5.0 - Build 23.20.16.4973' Renderer: 'Intel(R) HD Graphics 630'
  Pulsar/inspirations loaded Pulses: - InspirationsShared (Enabled/Forced)
                                     - InspirationsBuilding (Enabled/Not Forced)
                                     - InspirationsUtility (Enabled/Not Forced)
                                     - InspirationsTools (Enabled/Not Forced)
                                     - InspirationsRecipes (Enabled/Not Forced)
                                     - InspirationsTweaks (Enabled/Not Forced)
                                     - InspirationsShared (Enabled/Forced)
                                     - LeatherWorks (Enabled/Not Forced)
  Pulsar/tconstruct loaded Pulses: - TinkerCommons (Enabled/Forced)
                                   - TinkerWorld (Enabled/Not Forced)
                                   - TinkerTools (Enabled/Not Forced)
                                   - TinkerHarvestTools (Enabled/Forced)
                                   - TinkerMeleeWeapons (Enabled/Forced)
                                   - TinkerRangedWeapons (Enabled/Forced)
                                   - TinkerModifiers (Enabled/Forced)
                                   - TinkerSmeltery (Enabled/Not Forced)
                                   - TinkerGadgets (Enabled/Not Forced)
                                   - TinkerOredict (Enabled/Forced)
                                   - TinkerIntegration (Enabled/Forced)
                                   - TinkerFluids (Enabled/Forced)
                                   - TinkerMaterials (Enabled/Forced)
                                   - TinkerModelRegister (Enabled/Forced)
                                   - chiselsandbitsIntegration (Enabled/Not Forced)
                                   - quarkIntegration (Enabled/Not Forced)
  HammerCore Debug Information: Dependent Mods:
                                    -Improvable Skills (improvableskills) @65r
  Suspected Mods: Mystical Lib (mysticallib)
  Launched Version: forge-14.23.5.2847
  LWJGL: 2.9.4
  OpenGL: Intel(R) HD Graphics 630 GL version 4.5.0 - Build 23.20.16.4973, Intel
  GL Caps: Using GL 1.3 multitexturing.
           Using GL 1.3 texture combiners.
           Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
           Shaders are available because OpenGL 2.1 is supported.
           VBOs are available because OpenGL 1.5 is supported.
  Using VBOs: Yes
  Is Modded: Definitely; Client brand changed to 'fml,forge'
  Type: Client (map_client.txt)
  Resource Packs: 
  Current Language: English (US)
  Profiler Position: N/A (disabled)
  CPU: 8x Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz

**Comment by GreyMario** [comment]
Install **Just Enough IDs**.

And... ..consider thinking about where you're going with the modpack you're building.

**Comment by noobanidus** [comment]
I accidentally deleted a comment that suggested install Just Enough IDs. Beware that it is not a 100% guaranteed solution.

Your issue is that you have reached the limit of blocks  that is hard-coded into the game -- 4096. This limitation can be overcome with mods, but they have downsides. Just Enough IDs is better than Not Enough IDs (at least as far as I'm aware) in that it ports 1.13 code back into 1.12, and is considered More Robust.

Your other solution is to reduce some of the mods that you have installed. **Beware**, doing so in a pre-existing world will not allow that world to load, as the IDs have already been "reserved". You will have to start a new world in that case.
