### ISSUE TITLE
MysticalLib reports as 1.1.1 regardless of version

### ISSUE THREAD

**Issue by DoomRater** [MysticMods/MysticalLib#41]
### General Information

**Describe the bug:**
Checking the version MysticalLib reports to mods that check returns 1.1.1, even when the version the filename reports is 1.6.0.

**To Reproduce:**
Start up modded Minecraft, go to the mods list, and look at MysticalLib in the mod list.  Version: 1.1.1 (1.12.2 1.x.x) will show up.

Tested with 1.6.0 and the alpha version being used to test Roots 3.1.0 alphas.

**Comment by noobanidus** [comment]
a) Does it still do this?

I'm pretty sure I got the version field i n MysticalLib.java *and* the version replacements are set up properly in mcmod.info...

**Comment by DoomRater** [comment]
I have checked the alpha version I last tested as well as the last released version and both appear to report correctly to MultiMC. I think we're good here.
