### ISSUE TITLE
Latest version for 1.15.2 crashes when loading game

### ISSUE THREAD

**Issue by GrifVindh** [MysticMods/MysticalLib#42]
### General Information

**Describe the bug:**
After installing traverse-1.15.2-3.1.0, the game crashes when starting up. When I replace -3.1.0 with the older 3.0.0, the game loads normally.

**To Reproduce:**
1. Place traverse-1.15.2-3.1.0 in mods folder (remove older version if applicable) 
2. Launch minecraft
3. Game will crash while loading mods, return to initial launcher screen

**Expected behavior:**
After loading mods, splash screen displays.

***

### Environment Versions

Minecraft 1.15.2 with 1.15.2-forge-31.2.0

**Mystic Mods Versions**
- MysticalLib:  mysticallib-1.15.2-2.0.0

**Other Versions:**
- Forge: 1.15.2-forge-31.2.0
- Minecraft: 1.15.2

**Comment by noobanidus** [comment]
I need a crash report or latest.log or both, but I'll attempt to reproduce locally.

**Comment by GrifVindh** [comment]
... it looks like the latest release of Traverse fixed it. I'd intended to submit a bug for this over there... Iooks like I got turned around somewhere and submitted it for mysticallib instead. Sorry about that.

**Comment by noobanidus** [comment]
No worries!
