### ISSUE TITLE
I don't know what it means but the last loaded mod is mysticallib

### ISSUE THREAD

**Issue by Quadruplay** [MysticMods/MysticalLib#44]
---- Minecraft Crash Report ----
// Why did you do that?

Time: 2020-05-23 12:43:32 CEST
Description: Initializing game

java.lang.IllegalAccessError: tried to access class org.spongepowered.asm.mixin.transformer.MixinTransformer from class net.minecraftforge.fml.common.Loader
    at net.minecraftforge.fml.common.Loader.handler$zza000$beforeConstructingMods(Loader.java:1132)
    at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:594)
    at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:232)
    at net.minecraft.client.Minecraft.init(Minecraft.java:467)
    at net.minecraft.client.Minecraft.run(Minecraft.java:3931)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
  Minecraft Version: 1.12.2
  Operating System: Windows 10 (amd64) version 10.0
  Java Version: 1.8.0_51, Oracle Corporation
  Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
  Memory: 432491440 bytes (412 MB) / 939524096 bytes (896 MB) up to 6442450944 bytes (6144 MB)
  JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx6G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
  IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
  FML: MCP 9.42 Powered by Forge 14.23.5.2854 100 mods loaded, 100 mods active
       States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
       
       | State | ID                                   | Version           | Source                                        | Signature                                |
       |:----- |:------------------------------------ |:----------------- |:--------------------------------------------- |:---------------------------------------- |
       | L     | minecraft                            | 1.12.2            | minecraft.jar                                 | None                                     |
       | L     | mcp                                  | 9.42              | minecraft.jar                                 | None                                     |
       | L     | FML                                  | 8.0.99.99         | forge-1.12.2-14.23.5.2854.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | L     | forge                                | 14.23.5.2854      | forge-1.12.2-14.23.5.2854.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | L     | foamfixcore                          | 7.7.4             | minecraft.jar                                 | None                                     |
       | L     | aeadditions                          | 1.2               | aeadditions-1.12.2-1.2.jar                    | None                                     |
       | L     | aether_legacy                        | 1.4.4             | aether_legacy-1.12.2-v1.4.4.jar               | None                                     |
       | L     | aether_legacy_addon                  | 1.12.2-v1.2.3     | aether_continuation-1.12.2-v1.2.3.jar         | None                                     |
       | L     | ebwizardry                           | 4.2.10            | ElectroblobsWizardry-4.2.10-MC1.12.2.jar      | None                                     |
       | L     | ancientspellcraft                    | 1.0.1             | AncientSpellcraft-1.12.2-1.0.1.jar            | None                                     |
       | L     | anvilpatch                           | 1.0.0             | anvilpatch-1.0.0.jar                          | None                                     |
       | L     | arcane_essentials                    | 1.0               | Arcane+Essentials-0.9.2 (1).jar               | None                                     |
       | L     | baubles                              | 1.5.2             | Baubles-1.12-1.5.2.jar                        | None                                     |
       | L     | astralsorcery                        | 1.10.22           | astralsorcery-1.12.2-1.10.23.jar              | None                                     |
       | L     | attributefix                         | 1.0.4             | AttributeFix-1.12.2-1.0.4.jar                 | None                                     |
       | L     | atum                                 | 2.0.16            | Atum-1.12.2-2.0.16.jar                        | None                                     |
       | L     | xaerobetterpvp                       | 1.18.4            | Better-PvP-Mod-1.12.2.jar                     | None                                     |
       | L     | betteradvancements                   | 0.1.0.77          | BetterAdvancements-1.12.2-0.1.0.77.jar        | None                                     |
       | L     | bsb                                  | 1.0               | BetweenlandsStorage.jar                       | None                                     |
       | L     | redstoneflux                         | 2.1.0             | RedstoneFlux-1.12-2.1.0.6-universal.jar       | None                                     |
       | L     | cofhcore                             | 4.6.3             | CoFHCore-1.12.2-4.6.3.27-universal.jar        | None                                     |
       | L     | cofhworld                            | 1.3.1             | CoFHWorld-1.12.2-1.3.1.7-universal.jar        | None                                     |
       | L     | jei                                  | 4.15.0.291        | jei_1.12.2-4.15.0.291.jar                     | None                                     |
       | L     | tombmanygraves                       | 1.12-4.2.0        | TombManyGraves-1.12-4.2.0.jar                 | None                                     |
       | L     | thebetweenlands                      | 3.5.7             | TheBetweenlands-3.5.7-universal.jar           | None                                     |
       | L     | betweenores                          | 1.4.2             | BetweenOres-1.4.2.jar                         | None                                     |
       | L     | patchouli                            | 1.0-20            | Patchouli-1.0-20.jar                          | None                                     |
       | L     | thaumcraft                           | 6.1.BETA26        | Thaumcraft-1.12.2-6.1.BETA26 (1).jar          | None                                     |
       | L     | bewitchment                          | 0.21.12           | bewitchment-1.12.2-0.0.21.12.jar              | None                                     |
       | L     | blue_skies                           | 1.1.3             | blue_skies-1.12.2-v1.1.3 (1).jar              | None                                     |
       | L     | bountifulbaubles                     | 0.0.1             | Bountiful+Baubles-1.12.2-0.1.4.jar            | None                                     |
       | L     | bmtr                                 | 0.4               | BringMeTheRings-0.4.jar                       | None                                     |
       | L     | bullseye                             | 3.0.7             | Bullseye-1.12.2-3.0.7.jar                     | None                                     |
       | L     | carbonado                            | 1.5.1             | carbonado-1.5.1-mc1.12.x.jar                  | None                                     |
       | L     | chunkpregenerator                    | 2.1               | Chunk+Pregenerator+V1.12-2.2.jar              | None                                     |
       | L     | chunkanimator                        | 1.2               | ChunkAnimator-MC1.12-1.2.jar                  | None                                     |
       | L     | codechickenlib                       | 3.2.3.358         | CodeChickenLib-1.12.2-3.2.3.358-universal.jar | None                                     |
       | L     | cosmeticarmorreworked                | 1.12.2-v3         | CosmeticArmorReworked-1.12.2-v3.jar           | None                                     |
       | L     | cosmeticarmorreworked|tombmanygraves | 1.12.2-v3         | CosmeticArmorReworked-1.12.2-v3.jar           | None                                     |
       | L     | craftablechainmail                   | 1.0               | craftablechainmail-1.0.jar                    | None                                     |
       | L     | ctm                                  | MC1.12.2-1.0.1.30 | CTM-MC1.12.2-1.0.1.30.jar                     | None                                     |
       | L     | enchdesc                             | 1.1.15            | EnchantmentDescriptions-1.12.2-1.1.15.jar     | None                                     |
       | L     | enderportaldecoration                | 0.0.1             | EnderPortalDecoration-1.12.2-0.0.1.jar        | None                                     |
       | L     | enderstorage                         | 2.4.6.137         | EnderStorage-1.12.2-2.4.6.137-universal.jar   | None                                     |
       | L     | endportrec                           | 1.0               | endportrec_1.12-1.0.jar                       | None                                     |
       | L     | erebus                               | 1.0.31            | Erebus-1.0.31.jar                             | None                                     |
       | L     | moa_dlc                              | v1.2.0            | extra-moas-v1.2.0.jar                         | None                                     |
       | L     | minerva                              | 1.0.13            | minerva-library-1.0.13 (1).jar                | None                                     |
       | L     | extraalchemy                         | 0.5.3             | extraalchemy-0.5.3.jar                        | None                                     |
       | L     | extra_spells                         | 1.1.4             | ExtraSpells-1.12.2-1.1.4 (1).jar              | None                                     |
       | L     | foamfix                              | 0.10.10-1.12.2    | foamfix-0.10.10-1.12.2.jar                    | None                                     |
       | L     | forgelin                             | 1.8.4             | Forgelin-1.8.4.jar                            | None                                     |
       | L     | ftblib                               | 5.4.7.0           | FTBLib-5.4.7.0.jar                            | None                                     |
       | L     | ftbguides                            | 2.0.0.52          | FTBGuides-2.0.0.52.jar                        | None                                     |
       | L     | itemfilters                          | 1.0.3.12          | ItemFilters-1.0.3.12.jar                      | None                                     |
       | L     | ftbquests                            | 1.8.0.237         | FTBQuests-1.8.0.237 (1).jar                   | None                                     |
       | L     | ftbmoney                             | 1.1.0.42          | FTBMoney-1.1.0.42 (1).jar                     | None                                     |
       | L     | galaxite                             | 1.1.2             | galaxite-1.1.2-mc1.12.x.jar                   | None                                     |
       | L     | waila                                | 1.8.26            | Hwyla-1.8.26-B41_1.12.2.jar                   | None                                     |
       | L     | llibrary                             | 1.7.19            | llibrary-1.7.19-1.12.2.jar                    | None                                     |
       | L     | iceandfire                           | 1.9.1             | iceandfire-1.9.1-1.12.2.jar                   | None                                     |
       | L     | ichunutil                            | 7.2.2             | iChunUtil-1.12.2-7.2.2.jar                    | None                                     |
       | L     | illagerspell                         | 1.2               | illagerspell-1.12.2-1.2.jar                   | None                                     |
       | L     | jetif                                | 1.5.1             | jetif-1.12.2-1.5.1.jar                        | None                                     |
       | L     | jmh                                  | 2.1               | jmh_1.12-2.1.jar                              | None                                     |
       | L     | jeid                                 | 1.0.3-48          | JustEnoughIDs-1.0.3-48 (1).jar                | None                                     |
       | L     | jeresources                          | 0.9.2.60          | JustEnoughResources-1.12.2-0.9.2.60.jar       | None                                     |
       | L     | letsencryptcraft                     | @VERSION@         | letsencryptcraft-1.10.2-1.2.0.jar             | None                                     |
       | L     | libraryex                            | 1.0.12            | LibraryEx-1.12.2-1.0.12 (1).jar               | None                                     |
       | L     | lost_aether                          | 1.0.1             | lost-aether-content-1.12.2-1.0.1.jar          | None                                     |
       | L     | megaloot                             | 0.2.40            | megaloot-1.12.2-0.2.40 (1).jar                | None                                     |
       | L     | testdummy                            | 1.12              | MmmMmmMmmMmm-1.12-1.14.jar                    | None                                     |
       | L     | roots                                | 1.12.2-3.0.28     | Roots-1.12.2-3.0.28.jar                       | None                                     |
       | L     | mysticalworld                        | 1.12.2-1.8.4      | mysticalworld-1.12.2-1.8.4.jar                | None                                     |
       | L     | netherchest                          | 1.1.1             | netherchest-1.1.1.jar                         | None                                     |
       | L     | nethercraft                          | 1.0.2             | nethercraft-1.12.2-1.0.2 (2).jar              | None                                     |
       | L     | pitweaks                             | 1.12-1.1.1        | PiTweaks-1.12-1.1.1.jar                       | None                                     |
       | L     | potioncore                           | 1.9_for_1.12.2    | PotionCore-1.9_for_1.12.2.jar                 | None                                     |
       | L     | resourceloader                       | 1.5.3             | ResourceLoader-MC1.12.1-1.5.3.jar             | None                                     |
       | L     | roguelike                            | 1.8.0             | RoguelikeDungeons-1.12.2-1.8.0.jar            | None                                     |
       | L     | t3s4ebw                              | 1.0               | SeedsForWizardry+1.0+For+MC+Forge+1.12.2.jar  | None                                     |
       | L     | silkyspawners                        | 1.3               | silkyspawners-1.3.jar                         | None                                     |
       | L     | somanyenchantments                   | 0.4.3             | somanyenchantments+V0.4.31 (1).jar            | None                                     |
       | L     | surge                                | 2.0.77            | Surge-1.12.2-2.0.77 (1).jar                   | None                                     |
       | L     | tc6aspects4jei                       | 0.0.2a            | tc6aspects4jei-0.0.2a.jar                     | None                                     |
       | L     | texfix                               | 4.0               | TexFix+V-1.12-4.0.jar                         | None                                     |
       | L     | twilightforest                       | 3.10.1013         | twilightforest-1.12.2-3.10.1013-universal.jar | None                                     |
       | L     | tfspellpack                          | 1.0               | TFSpellPack-1.0-MC1.12.2.jar                  | None                                     |
       | L     | thaumicjei                           | 1.6.0             | ThaumicJEI-1.12.2-1.6.0-27.jar                | None                                     |
       | L     | thaumicperiphery                     | 0.3.1             | thaumicperiphery-0.3.1.jar                    | None                                     |
       | L     | travellersboots                      | 1.0.4             | travellersboots-1.12.2-1.0.4.jar              | None                                     |
       | L     | xat                                  | 0.28.1            | Trinkets+and+Baubles-1.12.2-0.28.1.jar        | None                                     |
       | L     | vanillafix                           | 1.0.10-SNAPSHOT   | VanillaFix-1.0.10-99.jar                      | None                                     |
       | L     | vulcanite                            | 1.5.2             | vulcanite-1.5.2-mc1.12.x.jar                  | None                                     |
       | L     | wolfarmor                            | 2.2.3.6           | wolfarmor-1.12.2-2.2.3.1798-universal.jar     | None                                     |
       | L     | woolintostrings                      | 1.0.2             | WoolIntoStrings-1.12.2-1.0.2.jar              | None                                     |
       | L     | xpbook                               | v1.1.4            | xptome-1.12.2-v1.1.4 (1).jar                  | None                                     |
       | L     | densemetals                          | 2.0.0             | DenseMetals-1.12.2-2.0.0.30.jar               | None                                     |
       | L     | phosphor-lighting                    | 1.12.2-0.2.6      | phosphor-1.12.2-0.2.6+build50-universal.jar   | None                                     |
       | L     | mysticallib                          | 1.12.2-1.7.0      | mysticallib-1.12.2-1.7.0.jar                  | None                                     |
  Loaded coremods (and transformers): TheBetweenlandsLoadingPlugin (TheBetweenlands-3.5.7-core.jar)
                                        thebetweenlands.core.TheBetweenlandsClassTransformer
                                      CTMCorePlugin (CTM-MC1.12.2-1.0.1.30.jar)
                                        team.chisel.ctm.client.asm.CTMTransformer
                                      ForgelinPlugin (Forgelin-1.8.4.jar)
                                        
                                      AstralCore (astralsorcery-1.12.2-1.10.23.jar)
                                        
                                      JustEnoughIDs Extension Plugin (JustEnoughIDs-1.0.3-48 (1).jar)
                                        org.dimdev.jeid.JEIDTransformer
                                      iceandfire (iceandfire-1.9.1-1.12.2.jar)
                                        com.github.alexthe666.iceandfire.patcher.IceAndFireRuntimePatcher
                                      BewitchmentFMLLoadingPlugin (bewitchment-1.12.2-0.0.21.12.jar)
                                        
                                      llibrary (llibrary-core-1.0.11-1.12.2.jar)
                                        net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
                                        net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
                                      SurgeLoadingPlugin (Surge-1.12.2-2.0.77 (1).jar)
                                        
                                      PhosphorFMLLoadingPlugin (phosphor-1.12.2-0.2.6+build50-universal.jar)
                                        
                                      BringMeTheRings plugin (BringMeTheRings-0.4.jar)
                                        zabi.minecraft.bmtr.core.BaublesTransformer
                                      VanillaFixLoadingPlugin (VanillaFix-1.0.10-99.jar)
                                        
                                      Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.10-1.12.2.jar)
                                        pl.asie.foamfix.coremod.FoamFixTransformer
                                      LoadingPlugin (ResourceLoader-MC1.12.1-1.5.3.jar)
                                        lumien.resourceloader.asm.ClassTransformer
                                      LoadingPlugin (ChunkAnimator-MC1.12-1.2.jar)
                                        lumien.chunkanimator.asm.ClassTransformer
  GL info: ' Vendor: 'Intel' Version: '4.5.0 - Build 25.20.100.6576' Renderer: 'Intel(R) UHD Graphics 630'
  Suspected Mods: Unknown
  Launched Version: 1.12.2-forge-14.23.5.2854
  LWJGL: 2.9.4
  OpenGL: Intel(R) UHD Graphics 630 GL version 4.5.0 - Build 25.20.100.6576, Intel
  GL Caps: Using GL 1.3 multitexturing.
           Using GL 1.3 texture combiners.
           Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
           Shaders are available because OpenGL 2.1 is supported.
           VBOs are available because OpenGL 1.5 is supported.
  Using VBOs: Yes
  Is Modded: Definitely; Client brand changed to 'fml,forge'
  Type: Client (map_client.txt)
  Resource Packs: 
  Current Language: English (US)
  Profiler Position: N/A (disabled)
  CPU: 8x Intel(R) Core(TM) i5-8300H CPU @ 2.30GHz

**Comment by noobanidus** [comment]
a) Please post crash reports on gist.github.com or pastebin.com

b) This crash has to do with sponge mixins, which MysticalLib doesn't use. I'd suggest that there's an issue with two separate mods that are using different versions of mixins. You should be able to work them out from the coremods listed in the crash report.
