### ISSUE TITLE
1.12.2 Crashes at startup, latest version

### ISSUE THREAD

**Issue by TopCraft** [MysticMods/MysticalLib#45]
[2020-06-05-3.log](https://github.com/MysticMods/MysticalLib/files/4739219/2020-06-05-3.log)

The only mod it says LCE is mysticlib. Please help!

**Comment by GreyMario** [comment]
To summarize what we just banged out on the Discord, the pack's Mystical World is out of date (`1.12.2-1.3.2`; latest as of this posting is `1.12.2-1.8.4`).
