### ISSUE TITLE
Unknown crash, please help!

### ISSUE THREAD

**Issue by Delfite** [MysticMods/MysticalLib#46]
### General Information

**Describe the bug:**
Whenever I attempt to load my modpack through the curse launcher I keep getting a hard crash and I have no clue as to why.

**To Reproduce:**
Well I don't exactly know HOW to reproduce it other than to just boot up my modpack in it's current state and watch it hard crash (thanks VanillaFix for the help).

**Expected behavior:**
I expected the game to load normally as it did on 7/5/2020

***

### Environment Versions

**Mystic Mods Versions**
- MysticalLib: 1.7.0 (latest at the time of reporting)
- Blockcraftery: 1.3.1

**Other Versions:**
- Conflicting mod: Unsure
- Other mods you think could cause issues: Industrial Foregoing (explanation at bottom)
- Forge: 14.23.5.2854
- Minecraft: 1.12.2
- Modpack (if available): Home freakin' run! (Link at bottom)

***

### Logging Information

**Crash Report (if available):**
https://pastebin.com/JkMnEGUx

**Latest Log (if necessary):**
https://pastebin.com/C2C75vkn

***

### Additional Information
**Screenshots (if available):**
None sadly...

**Additional context (optional):**
I have for the most part, not changed any of the config settings for most of my installed mods. The only ones I have changed are for FoamFix, ExtremeReactors, The Thermal Suite, and Immersive Engineering I believe... All mods in the pack are up-to-date as of writing this.

As for Industrial Foregoing, I was getting a crash with TeslaLib and IF while they were enabled. However, immediately after removing the two mods I started getting crashes from MysticalLib! I've already opened up an issue on the IF issue tracker for why it could've caused the crash. If you go looking for it, it should be Issue #795 just in case you need info from there.

Please get this fixed soon, blockcraftery blocks would look nice in my base!

**Comment by GreyMario** [comment]
```
java.lang.RuntimeException: Invalid id 4096 - maximum id range exceeded.
    at net.minecraftforge.registries.ForgeRegistry.add(ForgeRegistry.java:295)
```

Install Just Enough IDs or uninstall some mods that register blocks.

**Comment by Delfite** [comment]
Oh thanks a bunch, hopefully this fixes BOTH of the crashes I was experiencing
