### ISSUE TITLE
A Crash While Loading Mc

### ISSUE THREAD

**Issue by bruhmoment121** [MysticMods/MysticalLib#48]
I Got A Crash Involving Mysticallib

I expected It To Load Like My Other Modpacks

I Tried Both 1.9.0 and 1.7.0

My Installed Mystical Mods
- MysticalLib: 
- Mystical World

**Other Versions:**
- Conflicting mod ; None
- Other mods you think could cause issues: none
- Forge : 14.23.5.2854
- Minecraft: 1.12.2

Crash Report (if available):
https://paste.ee/p/HD0jB

**Comment by GreyMario** [comment]
Have you tried reading the reason for the crash itself?
```
java.lang.RuntimeException: Invalid id 4096 - maximum id range exceeded.
	at net.minecraftforge.registries.ForgeRegistry.add(ForgeRegistry.java:295)
```
You've run out of block IDs because the pack you're building is getting a bit big. Install JustEnoughIDs to fix this.

**Comment by noobanidus** [comment]
Thanks @GreyMario, that indeed looks to be the issue.

**Comment by bruhmoment121** [comment]
Thanks
