### ISSUE TITLE
Mysticallib Crashes.

### ISSUE THREAD

**Issue by DitMeisjeIsRaar** [MysticMods/MysticalLib#49]
Mysticallib keeps crashing, i tried a different version of both Mysticallib and Forge but keeps crashing.

Crash report:
---- Minecraft Crash Report ----

WARNING: coremods are present:
  ForgelinPlugin (Forgelin-1.8.3.jar)
  llibrary (llibrary-core-1.0.11-1.12.2.jar)
  BetterFoliageLoader (BetterFoliage-MC1.12-2.3.1.jar)
  SSLoadingPlugin (SereneSeasons-1.12.2-1.2.18-universal.jar)
  CorePlugin (SmoothFont-mc1.12.2-2.1.2.jar)
  CTMCorePlugin (CTM-MC1.12.2-1.0.2.31.jar)
  LoadingPlugin (Bloodmoon-MC1.12.2-1.5.3.jar)
Contact their authors BEFORE contacting forge

// This doesn't make any sense!

Time: 12/18/20 10:59 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Mystical Lib (mysticallib)
Caused by: java.lang.NoSuchMethodError: epicsquid.mysticallib.LibRegistry.addSlabPair(Lnet/minecraft/block/material/Material;Lnet/minecraft/block/SoundType;FLjava/lang/String;Lnet/minecraft/block/state/IBlockState;[Lnet/minecraft/block/Block;Lnet/minecraft/creativetab/CreativeTabs;)V
	at epicsquid.mysticalworld.init.ModBlocks.registerBlocks(ModBlocks.java:39)
	at epicsquid.mysticalworld.RegistryManager.init(RegistryManager.java:23)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_379_RegistryManager_init_RegisterContentEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at epicsquid.mysticallib.LibRegistry.initAll(LibRegistry.java:83)
	at epicsquid.mysticallib.proxy.CommonProxy.preInit(CommonProxy.java:14)
	at epicsquid.mysticallib.proxy.ClientProxy.preInit(ClientProxy.java:24)
	at epicsquid.mysticallib.MysticalLib.preInit(MysticalLib.java:30)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
	at sun.reflect.GeneratedMethodAccessor8.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:629)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 970395648 bytes (925 MB) / 2147483648 bytes (2048 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2854 Optifine OptiFine_1.12.2_HD_U_F5 58 mods loaded, 58 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID               | Version           | Source                                           | Signature                                |
	|:----- |:---------------- |:----------------- |:------------------------------------------------ |:---------------------------------------- |
	| LCH   | minecraft        | 1.12.2            | minecraft.jar                                    | None                                     |
	| LCH   | mcp              | 9.42              | minecraft.jar                                    | None                                     |
	| LCH   | FML              | 8.0.99.99         | forge-1.12.2-14.23.5.2854.jar                    | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | forge            | 14.23.5.2854      | forge-1.12.2-14.23.5.2854.jar                    | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | smoothfontcore   | mc1.12.2-2.1.2    | minecraft.jar                                    | None                                     |
	| LCH   | smoothfont       | mc1.12.2-2.1.2    | SmoothFont-mc1.12.2-2.1.2.jar                    | None                                     |
	| LCH   | thedragonlib     | 1.12.2-5.3.0      | thedragonlib-1.12.2-5.3.0.jar                    | None                                     |
	| LCH   | armorplus        | 1.12.2-11.28.0.69 | armorplus-1.12.2-11.28.0.69.jar                  | None                                     |
	| LCH   | babymobs         | 1.5.5             | BabyMobs-1.12-1.5.5.jar                          | None                                     |
	| LCH   | baubles          | 1.5.2             | Baubles-1.12-1.5.2.jar                           | None                                     |
	| LCH   | forgelin         | 1.8.3             | Forgelin-1.8.3.jar                               | None                                     |
	| LCH   | betterfoliage    | 2.3.1             | BetterFoliage-MC1.12-2.3.1.jar                   | None                                     |
	| LCH   | biomesoplenty    | 7.0.1.2444        | Biomes-O-Plenty-Mod-1.12.2.jar                   | None                                     |
	| LCH   | blockcraftery    | 1.12.2-1.3.1      | blockcraftery-1.12.2-1.3.1.jar                   | None                                     |
	| LCH   | bloodmoon        | 1.5.3             | Bloodmoon-MC1.12.2-1.5.3.jar                     | d72e0dd57935b3e9476212aea0c0df352dd76291 |
	| LCH   | bookshelf        | 2.3.589           | Bookshelf-1.12.2-2.3.589.jar                     | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCH   | bountifulbaubles | 0.0.1             | Bountiful+Baubles-1.12.2-0.1.6.jar               | None                                     |
	| LCH   | ctm              | MC1.12.2-1.0.2.31 | CTM-MC1.12.2-1.0.2.31.jar                        | None                                     |
	| LCH   | mysticalworld    | 1.12.2-1.8.4      | mysticalworld-1.12.2-1.8.4.jar                   | None                                     |
	| LCH   | chisel           | MC1.12.2-1.0.2.45 | Chisel-MC1.12.2-1.0.2.45.jar                     | None                                     |
	| LCH   | cqrepoured       | 2.1.3B            | Chocolate_Quest_Repoured-1.12.2-2.1.3B.jar       | None                                     |
	| LCH   | comfycozy        | 1.1               | comfycozy-1.1.jar                                | None                                     |
	| LCH   | ptrmodellib      | 1.0.4             | PTRLib-1.0.4.jar                                 | None                                     |
	| LCH   | props            | 2.6.3             | Decocraft-2.6.3_1.12.2.jar                       | None                                     |
	| LCH   | disenchanter     | 1.7               | disenchanter[1.12]1.7.jar                        | None                                     |
	| LCH   | mocreatures      | 12.0.5            | DrZharks+MoCreatures+Mod-12.0.5.jar              | None                                     |
	| LCH   | dynamictrees     | 1.12.2-0.9.21     | DynamicTrees-1.12.2-0.9.21.jar                   | None                                     |
	| LCH   | eplus            | 5.0.176           | EnchantingPlus-1.12.2-5.0.176.jar                | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCH   | fairylights      | 2.1.10            | fairylights-2.1.10-1.12.2.jar                    | None                                     |
	| LCH   | farlanders       | 1.0.1             | farlanders-1.12.2-1.0.1.jar                      | None                                     |
	| LCH   | cfm              | 6.3.1             | furniture-6.3.1-1.12.2.jar                       | None                                     |
	| LCH   | waila            | 1.8.26            | Hwyla-1.8.26-B41_1.12.2.jar                      | None                                     |
	| LCH   | ichunutil        | 7.2.2             | iChunUtil-1.12.2-7.2.2.jar                       | 4db5c2bd1b556f252a5b8b54b256d381b2a0a6b8 |
	| LCH   | inventorypets    | 2.0.6             | inventorypets-1.12-2.0.6.jar                     | None                                     |
	| LCH   | ironchest        | 1.12.2-7.0.67.844 | ironchest-1.12.2-7.0.72.847.jar                  | None                                     |
	| LCH   | journeymap       | 1.12.2-5.7.1      | journeymap-1.12.2-5.7.1.jar                      | None                                     |
	| LCH   | mca              | 6.1.0             | MCA-1.12.2-6.1.0-universal.jar                   | None                                     |
	| LCH   | moarsigns        | 6.0.0.11          | MoarSigns-1.12.2-6.0.0.11.jar                    | 5a57c7d1420cf4c58f53ea2a298ebef8215ede63 |
	| LCH   | morph            | 7.2.0             | Morph-1.12.2-7.2.1.jar                           | 4db5c2bd1b556f252a5b8b54b256d381b2a0a6b8 |
	| LCH   | mo_swords        | v5                | moSwords-1.12.2v5.jar                            | None                                     |
	| LCH   | llibrary         | 1.7.20            | llibrary-1.7.20-1.12.2.jar                       | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
	| LCH   | mowziesmobs      | 1.5.8             | mowziesmobs-1.5.8.jar                            | None                                     |
	| LCH   | multimob         | 1.0.5             | multimob-1.0.5.jar                               | None                                     |
	| LCH   | naturescompass   | 1.8.3             | NaturesCompass-1.12.2-1.8.3.jar                  | None                                     |
	| LCH   | harvestcraft     | 1.12.2zb          | Pam's+HarvestCraft+1.12.2zg.jar                  | None                                     |
	| LCH   | getalltheseeds   | 1.12a             | Pams-Get-all-the-Seeds-Mod-1.12.2.jar            | None                                     |
	| LCH   | pamscookables    | 1.1               | pamscookables-1.1.jar                            | None                                     |
	| LCH   | patchouli        | 1.0-20            | Patchouli-1.0-20.jar                             | None                                     |
	| LCH   | primitivemobs    | 1.2.3a            | primitivemobs-1.2.3a.jar                         | None                                     |
	| LCH   | sereneseasons    | 1.2.18            | SereneSeasons-1.12.2-1.2.18-universal.jar        | None                                     |
	| LCH   | torohealthmod    | 1.12.2-11         | torohealth-1.12.2-11.jar                         | None                                     |
	| LCH   | treechopper      | 1.2.4             | TreeChopper-1.12.2-1.2.4.jar                     | None                                     |
	| LCH   | twilightforest   | 3.11.1020         | twilightforest-1.12.2-3.11.1020-universal[1].jar | None                                     |
	| LCH   | uteamcore        | 2.2.5.147         | u_team_core-1.12.2-2.2.5.147.jar                 | None                                     |
	| LCH   | usefulbackpacks  | 1.5.3.59          | useful_backpacks-1.12.2-1.5.3.59.jar             | None                                     |
	| LCH   | wawla            | 2.6.275           | Wawla-1.12.2-2.6.275.jar                         | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCH   | weeeflowers      | 1.12.2b           | Weee-Flowers-Mod-1.12.2.jar                      | None                                     |
	| LCE   | mysticallib      | 1.12.2-1.3.0      | mysticallib-1.12.2-1.3.0.jar                     | None                                     |

	Loaded coremods (and transformers): 
ForgelinPlugin (Forgelin-1.8.3.jar)
  
llibrary (llibrary-core-1.0.11-1.12.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
BetterFoliageLoader (BetterFoliage-MC1.12-2.3.1.jar)
  mods.betterfoliage.loader.BetterFoliageTransformer
SSLoadingPlugin (SereneSeasons-1.12.2-1.2.18-universal.jar)
  sereneseasons.asm.transformer.EntityRendererTransformer
  sereneseasons.asm.transformer.WorldTransformer
CorePlugin (SmoothFont-mc1.12.2-2.1.2.jar)
  bre.smoothfont.asm.Transformer
CTMCorePlugin (CTM-MC1.12.2-1.0.2.31.jar)
  team.chisel.ctm.client.asm.CTMTransformer
LoadingPlugin (Bloodmoon-MC1.12.2-1.5.3.jar)
  lumien.bloodmoon.asm.ClassTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 445.87' Renderer: 'GeForce RTX 2070/PCIe/SSE2'
	OptiFine Version: OptiFine_1.12.2_HD_U_F5
	OptiFine Build: 20191204-141934
	Render Distance Chunks: 12
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 445.87
	OpenGlRenderer: GeForce RTX 2070/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 12

**Comment by noobanidus** [comment]
I'd recommend going directly to CurseForge and downloading the latest versions of all of the mods.

- Please update Mystical World to 1.9.2 (you have 1.8 or earlier).
- If you've also got Roots (I didn't see it), please make sure you're running Roots 3.0.32.
- Finally, please make sure you're running 1.9.0 of MysticalLib.

**Comment by DitMeisjeIsRaar** [comment]
Thanks it worked! I updated Mystical World to 1.9.2 and updated MysticalLib to 1.9.0 . Issue is solved thanks
