### ISSUE TITLE
Mysticallib keeps crashing

### ISSUE THREAD

**Issue by MianReplicate** [MysticMods/MysticalLib#50]
### General Information

**Describe the bug:**
When I start up mc with mysticallib the game just crashes. It crashes with or without any mods.

**To Reproduce:**
1. Start up minecraft with mysticallib

**Expected behavior:**
Minecraft to start up normally.

### Environment Versions
MC 1.12.2

**Mystic Mods Versions**

- MysticalLib: 1.12.2-1.1.0.0
- MysticalWorld: 1.12.2-1.9.3

**Other Versions:**
- Forge: 1.12.2-forge-14.23.5.2854
- Minecraft: 1.12.2

**Crash Report (if available):**
[crash-2021-03-18_18.43.37-client.txt](https://github.com/MysticMods/MysticalLib/files/6168138/crash-2021-03-18_18.43.37-client.txt)

**Latest Log (if necessary):**
[latest.log](https://github.com/MysticMods/MysticalLib/files/6168141/latest.log)
***

**Comment by noobanidus** [comment]
This is an odd one. There appears to be some sort of material race condition in Mystical World, I'll look into it.

**Comment by noobanidus** [comment]
I've moved it to that tracker, linked above.

**Comment by noobanidus** [comment]
Okay, that's fixed with the release of 1.9.4 of Mystical World.
