### ISSUE TITLE
Clear this is an issue

### ISSUE THREAD

**Issue by Connorray1234** [MysticMods/MysticalLib#55]
![Screenshot_739](https://user-images.githubusercontent.com/85777151/136485281-2afa904a-4e2e-4802-bcf4-a62ed72fff35.jpg)
Welt this may need no explanation to what the issue is

**Comment by noobanidus** [comment]
Please directly download Roots 3.1.4, it should be available on CurseForge now but it might not be available on the launcher just yet.

EDIT: That mod fixes the dependency issue.
