### ISSUE TITLE
what version of mysticallib uses forge 14.23.5.2768 please help!

### ISSUE THREAD

**Issue by Dr1ve65** [MysticMods/MysticalLib#58]
so im getting back into playing an old world and it needed blockcraftery because of some building i had built there

anyways i went to download mysticallib and got the latest version but on startup it told me i had an outdated version of forge and that i needed 14.23.5.2847 or above
ive tried all versions of mysticallib from latest to 1.6.0 and at this point im too frustrated to keep looking 

if anyone sees this please let me know what version i need im begging you!

(btw i am playing version 1.12.2 of minecraft)

**Comment by ByThePowerOfScience** [comment]
You need to update your forge version. All mods should work on a newer forge revision, but few can work on an older version than the one they were designed for.

You should see a green dot on your "Mods" button when you launch the game.  If you follow the green dot through the menus it'll tell you how to update.

Closed.
