### ISSUE TITLE
Crash when running on a server

### ISSUE THREAD

**Issue by Apocryphai** [MysticMods/MysticalLib#7]
No problems on a single-player, local instance, but when I install MysticalLib on a server I get the following crash: 

```
Description: Exception in server tick loop

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from MysticalLib (mysticallib)
Caused by: java.lang.NoSuchMethodError: epicsquid.mysticalworld.block.BlockThatch.setLayer(Lnet/minecraft/util/BlockRenderLayer;)Lepicsquid/mysticallib/block/BlockBase;

```

**Comment by EpicSquid** [comment]
Easy fix, I'll fix it asap

**Comment by EpicSquid** [comment]
Fixed in the newest build of mystical world. Just waiting on curseforge approval. Seehttps://github.com/EpicSquid/MysticalWorld/issues/2
