### ISSUE TITLE
elucent

### ISSUE THREAD

**Issue by generrosity** [MysticMods/MysticalLib#8]
The link to patreon on the curseforge page says epicsquid but links to elucent

😜 minor change, but just happened to be the one I clicked on to follow it through

Also - you are doing epic stuff. Its a 'issue' that you aren't hearing it often enough! Even if it is now a meme that you are picking up two mods a week 😜 rock on dude! Awesome to hear you on the dev streams of others too. And appreciation from the other side of the ditch.

**Comment by EpicSquid** [comment]
Thank you so much! This issue report might just have made my day. I'll fix up the patreon link asap, and thank you for all the kind words! :D

**Comment by EpicSquid** [comment]
Fixed! Again, thanks for the kind words, made my day.
