### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by Serifina** [MysticMods/MysticalLib#9]
Using the Blockcraftery and MysticalLib versions published today.

https://paste.dimdev.org/ojevumulah.mccrash

**Comment by EpicSquid** [comment]
Fixing now... This was an unfortunate oversight

**Comment by Serifina** [comment]
Thanks! At least someone caught it early, right?

**Comment by EpicSquid** [comment]
Waiting for approval now. Almost done
